global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: replicable-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8000

  - job_name: milvus
    metrics_path: /metrics
    static_configs:
      - targets:
          - milvus:9091

  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector:8889
